onChange handles SyntheticEvents and naked values...
Since converting from valueLink to onChange, our handlers are now
called with SyntheticEvent objects instead of the "naked" value.

This change (hack) lets the UnboundInput._onChange handler handle
both types of events.

Fixes this failing test in frigging-bootstrap:

```
  38) Basic form should call form onChange when any field changes:
     Error: Unsatisfied verification on test double.

  Wanted:
    - called with `({name: "Randy", city: "Toronto"})`.

  But was actually called:
    - called with `({name: "Randy", city: "[object Object]"})`.
```